# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tpm_types/tpm2b_sensitive_create.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'tpm_types/tpm2b_sensitive_create.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&tpm_types/tpm2b_sensitive_create.proto\x12\ttpm_types\")\n\tTPM2BAuth\x12\x0c\n\x04size\x18\x01 \x01(\r\x12\x0e\n\x06\x62uffer\x18\x02 \x01(\x0c\"2\n\x12TPM2BSensitiveData\x12\x0c\n\x04size\x18\x01 \x01(\r\x12\x0e\n\x06\x62uffer\x18\x02 \x01(\x0c\"k\n\x13TPMSSensitiveCreate\x12\'\n\tuser_auth\x18\x01 \x01(\x0b\x32\x14.tpm_types.TPM2BAuth\x12+\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x1d.tpm_types.TPM2BSensitiveData\"W\n\x14TPM2BSensitiveCreate\x12\x0c\n\x04size\x18\x01 \x01(\r\x12\x31\n\tsensitive\x18\x02 \x01(\x0b\x32\x1e.tpm_types.TPMSSensitiveCreateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tpm_types.tpm2b_sensitive_create_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TPM2BAUTH']._serialized_start=53
  _globals['_TPM2BAUTH']._serialized_end=94
  _globals['_TPM2BSENSITIVEDATA']._serialized_start=96
  _globals['_TPM2BSENSITIVEDATA']._serialized_end=146
  _globals['_TPMSSENSITIVECREATE']._serialized_start=148
  _globals['_TPMSSENSITIVECREATE']._serialized_end=255
  _globals['_TPM2BSENSITIVECREATE']._serialized_start=257
  _globals['_TPM2BSENSITIVECREATE']._serialized_end=344
# @@protoc_insertion_point(module_scope)
