# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tpm_types/tpml_pcr_selection.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'tpm_types/tpml_pcr_selection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from constants import tpm_alg_pb2 as constants_dot_tpm__alg__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"tpm_types/tpml_pcr_selection.proto\x12\ttpm_types\x1a\x17\x63onstants/tpm_alg.proto\"^\n\x10TPMSPCRSelection\x12\x1f\n\x04hash\x18\x01 \x01(\x0e\x32\x11.constants.TPMALG\x12\x15\n\rsizeof_select\x18\x02 \x01(\r\x12\x12\n\npcr_select\x18\x03 \x01(\x0c\"V\n\x10TPMLPCRSelection\x12\r\n\x05\x63ount\x18\x01 \x01(\r\x12\x33\n\x0epcr_selections\x18\x02 \x03(\x0b\x32\x1b.tpm_types.TPMSPCRSelectionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tpm_types.tpml_pcr_selection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TPMSPCRSELECTION']._serialized_start=74
  _globals['_TPMSPCRSELECTION']._serialized_end=168
  _globals['_TPMLPCRSELECTION']._serialized_start=170
  _globals['_TPMLPCRSELECTION']._serialized_end=256
# @@protoc_insertion_point(module_scope)
