# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tpm_types/tpmt_sym_def.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'tpm_types/tpmt_sym_def.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from constants import tpm_alg_pb2 as constants_dot_tpm__alg__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ctpm_types/tpmt_sym_def.proto\x12\ttpm_types\x1a\x17\x63onstants/tpm_alg.proto\"e\n\nTPMTSymDef\x12$\n\talgorithm\x18\x01 \x01(\x0e\x32\x11.constants.TPMALG\x12\x10\n\x08key_bits\x18\x02 \x01(\r\x12\x1f\n\x04mode\x18\x03 \x01(\x0e\x32\x11.constants.TPMALGb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tpm_types.tpmt_sym_def_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TPMTSYMDEF']._serialized_start=68
  _globals['_TPMTSYMDEF']._serialized_end=169
# @@protoc_insertion_point(module_scope)
