# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tpm_types/tpmt_rsa_decrypt.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'tpm_types/tpmt_rsa_decrypt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from constants import tpm_alg_pb2 as constants_dot_tpm__alg__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n tpm_types/tpmt_rsa_decrypt.proto\x12\ttpm_types\x1a\x17\x63onstants/tpm_alg.proto\"X\n\x0eTPMTRSADecrypt\x12!\n\x06scheme\x18\x01 \x01(\x0e\x32\x11.constants.TPMALG\x12#\n\x08hash_alg\x18\x02 \x01(\x0e\x32\x11.constants.TPMALGb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tpm_types.tpmt_rsa_decrypt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TPMTRSADECRYPT']._serialized_start=72
  _globals['_TPMTRSADECRYPT']._serialized_end=160
# @@protoc_insertion_point(module_scope)
