FROM debian:stable AS run

ENV DEBIAN_FRONTEND=noninteractive
ENV CXX=clang++
ENV CC=clang

RUN apt-get update -q && \
    apt-get install -y --no-install-recommends ca-certificates \
    openssl \
    git-core \
    libssl-dev \
    libclang-rt-dev \
    clang \
    llvm \
    cmake \
    ninja-build && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /srv/
WORKDIR /srv/

COPY . /srv/

RUN git submodule update --init
RUN cmake -B build -G Ninja -S /srv/fuzzer/
RUN cmake --build build

CMD ["/srv/scripts/start-fuzzer.sh"]
