FROM debian:stable AS run

ENV DEBIAN_FRONTEND=noninteractive
ENV CXX=clang++
ENV CC=clang

RUN apt-get update -q && \
    apt-get install -y --no-install-recommends ca-certificates \
    libssl-dev \
    libclang-rt-dev \
    clang \
    cmake \
    catch2 \
    ninja-build && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /srv/
WORKDIR /srv/

COPY . /srv/

RUN cmake -B build -G Ninja -S /srv/fuzzer/ -DRUN_UNIT_TESTS=ON
RUN cmake --build build

CMD ["ctest", "--test-dir", "build", "--verbose"]
