services:
  fuzzer:
    build:
      context: .
      dockerfile: Dockerfile
      target: fuzzer
    volumes:
      - ./corpus/bytearray:/srv/corpus
      - ./artifacts/bytearray:/srv/artifacts
      - ./coverage/bytearray:/srv/build/coverage
    environment:
      FUZZER_EXTRA_ARGS: -seed=38912891 -runs=100000
      GEN_COVERAGE: "1"
      FUZZER_BIN_NAME: "Fuzzer"
  proto-fuzzer:
    build:
      context: .
      dockerfile: Dockerfile
      target: fuzzer
    volumes:
      - ./corpus/proto:/srv/corpus
      - ./artifacts/proto:/srv/artifacts
      - ./coverage/proto:/srv/build/coverage
    environment:
      FUZZER_EXTRA_ARGS: -seed=38912891 -runs=100000
      GEN_COVERAGE: "1"
      FUZZER_BIN_NAME: "proto-fuzzer"
      SEEDS_DIR: "/srv/seeds/proto"
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
