# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tpm_commands/tpm_clear.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "tpm_commands/tpm_clear.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tpm_types import tpm_header_pb2 as tpm__types_dot_tpm__header__pb2
from tpm_types import tpm_session_pb2 as tpm__types_dot_tpm__session__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n\x1ctpm_commands/tpm_clear.proto\x12\x0ctpm_commands\x1a\x1atpm_types/tpm_header.proto\x1a\x1btpm_types/tpm_session.proto\"n\n\x08TPMClear\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.tpm_types.TPMHeader\x12\x13\n\x0b\x61uth_handle\x18\x02 \x01(\r\x12'\n\x08sessions\x18\x03 \x03(\x0b\x32\x15.tpm_types.TPMSessionb\x06proto3"
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "tpm_commands.tpm_clear_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_TPMCLEAR"]._serialized_start = 103
    _globals["_TPMCLEAR"]._serialized_end = 213
# @@protoc_insertion_point(module_scope)
