# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tpm_commands/tpm_makecredential.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'tpm_commands/tpm_makecredential.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tpm_types import tpm_header_pb2 as tpm__types_dot_tpm__header__pb2
from tpm_types import tpm2b_data_pb2 as tpm__types_dot_tpm2b__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%tpm_commands/tpm_makecredential.proto\x12\x0ctpm_commands\x1a\x1atpm_types/tpm_header.proto\x1a\x1atpm_types/tpm2b_data.proto\"\x9e\x01\n\x11TPMMakeCredential\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.tpm_types.TPMHeader\x12\x0e\n\x06handle\x18\x02 \x01(\r\x12(\n\ncredential\x18\x03 \x01(\x0b\x32\x14.tpm_types.TPM2BData\x12)\n\x0bobject_name\x18\x04 \x01(\x0b\x32\x14.tpm_types.TPM2BDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tpm_commands.tpm_makecredential_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TPMMAKECREDENTIAL']._serialized_start=112
  _globals['_TPMMAKECREDENTIAL']._serialized_end=270
# @@protoc_insertion_point(module_scope)
