# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tpm_commands/tpm_rsa_encrypt.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'tpm_commands/tpm_rsa_encrypt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tpm_types import tpm_header_pb2 as tpm__types_dot_tpm__header__pb2
from tpm_types import tpm2b_public_key_rsa_pb2 as tpm__types_dot_tpm2b__public__key__rsa__pb2
from tpm_types import tpmt_rsa_decrypt_pb2 as tpm__types_dot_tpmt__rsa__decrypt__pb2
from tpm_types import tpm2b_data_pb2 as tpm__types_dot_tpm2b__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"tpm_commands/tpm_rsa_encrypt.proto\x12\x0ctpm_commands\x1a\x1atpm_types/tpm_header.proto\x1a$tpm_types/tpm2b_public_key_rsa.proto\x1a tpm_types/tpmt_rsa_decrypt.proto\x1a\x1atpm_types/tpm2b_data.proto\"\xcb\x01\n\rTPMRSAEncrypt\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.tpm_types.TPMHeader\x12\x12\n\nkey_handle\x18\x02 \x01(\r\x12-\n\x07message\x18\x04 \x01(\x0b\x32\x1c.tpm_types.TPM2BPublicKeyRSA\x12,\n\tin_scheme\x18\x05 \x01(\x0b\x32\x19.tpm_types.TPMTRSADecrypt\x12#\n\x05label\x18\x06 \x01(\x0b\x32\x14.tpm_types.TPM2BDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tpm_commands.tpm_rsa_encrypt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TPMRSAENCRYPT']._serialized_start=181
  _globals['_TPMRSAENCRYPT']._serialized_end=384
# @@protoc_insertion_point(module_scope)
