# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tpm_commands/tpm_create.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'tpm_commands/tpm_create.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tpm_types import tpm_header_pb2 as tpm__types_dot_tpm__header__pb2
from tpm_types import tpm2b_sensitive_create_pb2 as tpm__types_dot_tpm2b__sensitive__create__pb2
from tpm_types import tpm2b_public_pb2 as tpm__types_dot_tpm2b__public__pb2
from tpm_types import tpm2b_data_pb2 as tpm__types_dot_tpm2b__data__pb2
from tpm_types import tpml_pcr_selection_pb2 as tpm__types_dot_tpml__pcr__selection__pb2
from tpm_types import tpm_session_pb2 as tpm__types_dot_tpm__session__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dtpm_commands/tpm_create.proto\x12\x0ctpm_commands\x1a\x1atpm_types/tpm_header.proto\x1a&tpm_types/tpm2b_sensitive_create.proto\x1a\x1ctpm_types/tpm2b_public.proto\x1a\x1atpm_types/tpm2b_data.proto\x1a\"tpm_types/tpml_pcr_selection.proto\x1a\x1btpm_types/tpm_session.proto\"\xb2\x02\n\tTPMCreate\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.tpm_types.TPMHeader\x12\x15\n\rparent_handle\x18\x02 \x01(\r\x12\'\n\x08sessions\x18\x03 \x03(\x0b\x32\x15.tpm_types.TPMSession\x12\x35\n\x0cin_sensitive\x18\x04 \x01(\x0b\x32\x1f.tpm_types.TPM2BSensitiveCreate\x12)\n\tin_public\x18\x05 \x01(\x0b\x32\x16.tpm_types.TPM2BPublic\x12*\n\x0coutside_info\x18\x06 \x01(\x0b\x32\x14.tpm_types.TPM2BData\x12\x31\n\x0c\x63reation_pcr\x18\x07 \x01(\x0b\x32\x1b.tpm_types.TPMLPCRSelectionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tpm_commands.tpm_create_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TPMCREATE']._serialized_start=239
  _globals['_TPMCREATE']._serialized_end=545
# @@protoc_insertion_point(module_scope)
