# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tpm_commands/tpm_pcr_setauthpolicy.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'tpm_commands/tpm_pcr_setauthpolicy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tpm_types import tpm_header_pb2 as tpm__types_dot_tpm__header__pb2
from tpm_types import tpm_session_pb2 as tpm__types_dot_tpm__session__pb2
from tpm_types import tpm2b_digest_pb2 as tpm__types_dot_tpm2b__digest__pb2
from constants import tpm_alg_pb2 as constants_dot_tpm__alg__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(tpm_commands/tpm_pcr_setauthpolicy.proto\x12\x0ctpm_commands\x1a\x1atpm_types/tpm_header.proto\x1a\x1btpm_types/tpm_session.proto\x1a\x1ctpm_types/tpm2b_digest.proto\x1a\x17\x63onstants/tpm_alg.proto\"\xd9\x01\n\x13TPMPCRSetAuthPolicy\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.tpm_types.TPMHeader\x12\x13\n\x0b\x61uth_handle\x18\x02 \x01(\r\x12\'\n\x08sessions\x18\x03 \x03(\x0b\x32\x15.tpm_types.TPMSession\x12*\n\nauthPolicy\x18\x04 \x01(\x0b\x32\x16.tpm_types.TPM2BDigest\x12\"\n\x07hashAlg\x18\x05 \x01(\x0e\x32\x11.constants.TPMALG\x12\x0e\n\x06pcrNum\x18\x06 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tpm_commands.tpm_pcr_setauthpolicy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TPMPCRSETAUTHPOLICY']._serialized_start=171
  _globals['_TPMPCRSETAUTHPOLICY']._serialized_end=388
# @@protoc_insertion_point(module_scope)
