FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    tpm2-tools \
    xxd \
    tcpdump tshark \
    iproute2 netcat-openbsd \
    ca-certificates \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app
CMD ["/bin/bash"]
