# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: constants/tpm_cc.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'constants/tpm_cc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63onstants/tpm_cc.proto\x12\tconstants*\xd1\x06\n\x05TPMCC\x12\x16\n\x12TPM_CC_UNSPECIFIED\x10\x00\x12\x1d\n\x18TPM_CC_NV_UNDEFINE_SPACE\x10\xa2\x02\x12\x11\n\x0cTPM_CC_CLEAR\x10\xa6\x02\x12\x1b\n\x16TPM_CC_NV_DEFINE_SPACE\x10\xaa\x02\x12\x1a\n\x15TPM_CC_CREATE_PRIMARY\x10\xb1\x02\x12\x17\n\x12TPM_CC_NV_SET_BITS\x10\xb5\x02\x12\x15\n\x10TPM_CC_NV_EXTEND\x10\xb6\x02\x12\x14\n\x0fTPM_CC_NV_WRITE\x10\xb7\x02\x12\x19\n\x14TPM_CC_NV_WRITE_LOCK\x10\xb8\x02\x12\x15\n\x10TPM_CC_PCR_EVENT\x10\xbc\x02\x12\x15\n\x10TPM_CC_PCR_RESET\x10\xbd\x02\x12!\n\x1cTPM_CC_INCREMENTAL_SELF_TEST\x10\xc2\x02\x12\x15\n\x10TPM_CC_SELF_TEST\x10\xc3\x02\x12\x17\n\x12TPM_CC_STIR_RANDOM\x10\xc6\x02\x12\x13\n\x0eTPM_CC_NV_READ\x10\xce\x02\x12\x18\n\x13TPM_CC_NV_READ_LOCK\x10\xcf\x02\x12\x12\n\rTPM_CC_CREATE\x10\xd3\x02\x12\x10\n\x0bTPM_CC_LOAD\x10\xd7\x02\x12\x17\n\x12TPM_CC_RSA_DECRYPT\x10\xd9\x02\x12\x10\n\x0bTPM_CC_SIGN\x10\xdd\x02\x12\x12\n\rTPM_CC_UNSEAL\x10\xde\x02\x12\x19\n\x14TPM_CC_LOAD_EXTERNAL\x10\xe7\x02\x12\x17\n\x12TPM_CC_RSA_ENCRYPT\x10\xf4\x02\x12\x1e\n\x19TPM_CC_START_AUTH_SESSION\x10\xf6\x02\x12\x1a\n\x15TPM_CC_ECC_PARAMETERS\x10\xf8\x02\x12\x1a\n\x15TPM_CC_GET_CAPABILITY\x10\xfa\x02\x12\x16\n\x11TPM_CC_GET_RANDOM\x10\xfb\x02\x12\x1b\n\x16TPM_CC_GET_TEST_RESULT\x10\xfc\x02\x12\x10\n\x0bTPM_CC_HASH\x10\xfd\x02\x12\x14\n\x0fTPM_CC_PCR_READ\x10\xfe\x02\x12\x16\n\x11TPM_CC_READ_CLOCK\x10\x81\x03\x12\x16\n\x11TPM_CC_PCR_EXTEND\x10\x82\x03\x12\x16\n\x11TPM_CC_TEST_PARMS\x10\x8a\x03\x12\x1e\n\x16TPM_CC_VENDOR_TCG_TEST\x10\x80\x80\x80\x80\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'constants.tpm_cc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TPMCC']._serialized_start=38
  _globals['_TPMCC']._serialized_end=887
# @@protoc_insertion_point(module_scope)
