# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: constants/tpm_cc.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'constants/tpm_cc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63onstants/tpm_cc.proto\x12\tconstants*\x87\x01\n\x05TPMCC\x12\x16\n\x12TPM_CC_UNSPECIFIED\x10\x00\x12\x1a\n\x15TPM_CC_CREATE_PRIMARY\x10\xb1\x02\x12\x12\n\rTPM_CC_CREATE\x10\xd3\x02\x12\x1e\n\x19TPM_CC_START_AUTH_SESSION\x10\xf6\x02\x12\x16\n\x11TPM_CC_GET_RANDOM\x10\xfb\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'constants.tpm_cc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TPMCC']._serialized_start=38
  _globals['_TPMCC']._serialized_end=173
# @@protoc_insertion_point(module_scope)
