# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: constants/tpm_rh.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'constants/tpm_rh.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63onstants/tpm_rh.proto\x12\tconstants*c\n\x05TPMRH\x12\x16\n\x12TPM_RH_UNSPECIFIED\x10\x00\x12\x14\n\x0cTPM_RH_OWNER\x10\x81\x80\x80\x80\x04\x12\x13\n\x0bTPM_RH_NULL\x10\x87\x80\x80\x80\x04\x12\x17\n\x0fTPM_RH_PLATFORM\x10\x8c\x80\x80\x80\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'constants.tpm_rh_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TPMRH']._serialized_start=37
  _globals['_TPMRH']._serialized_end=136
# @@protoc_insertion_point(module_scope)
