# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tpm_commands.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'tpm_commands.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tpm_commands import tpm_getrandom_pb2 as tpm__commands_dot_tpm__getrandom__pb2
from tpm_commands import tpm_create_pb2 as tpm__commands_dot_tpm__create__pb2
from tpm_commands import tpm_createprimary_pb2 as tpm__commands_dot_tpm__createprimary__pb2
from tpm_commands import tpm_startauthsession_pb2 as tpm__commands_dot_tpm__startauthsession__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12tpm_commands.proto\x12\x03tpm\x1a tpm_commands/tpm_getrandom.proto\x1a\x1dtpm_commands/tpm_create.proto\x1a$tpm_commands/tpm_createprimary.proto\x1a\'tpm_commands/tpm_startauthsession.proto\"\xeb\x01\n\nTPMCommand\x12/\n\tgetrandom\x18\x01 \x01(\x0b\x32\x1a.tpm_commands.TPMGetRandomH\x00\x12)\n\x06\x63reate\x18\x02 \x01(\x0b\x32\x17.tpm_commands.TPMCreateH\x00\x12\x37\n\rcreateprimary\x18\x03 \x01(\x0b\x32\x1e.tpm_commands.TPMCreatePrimaryH\x00\x12=\n\x10startauthsession\x18\x04 \x01(\x0b\x32!.tpm_commands.TPMStartAuthSessionH\x00\x42\t\n\x07\x63ommand\"7\n\x12TPMCommandSequence\x12!\n\x08\x63ommands\x18\x01 \x03(\x0b\x32\x0f.tpm.TPMCommandb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tpm_commands_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TPMCOMMAND']._serialized_start=172
  _globals['_TPMCOMMAND']._serialized_end=407
  _globals['_TPMCOMMANDSEQUENCE']._serialized_start=409
  _globals['_TPMCOMMANDSEQUENCE']._serialized_end=464
# @@protoc_insertion_point(module_scope)
