name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-fuzzer:
    name: Build Fuzzer binary
    runs-on: ubuntu-24.04
    env:
      CC: clang-18
      CXX: clang++-18
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake ninja-build pkg-config \
            clang-18 \
            llvm \
            libssl-dev

          echo "Compiler:"
          ${CXX} --version
          echo "OpenSSL:"
          openssl version

      - name: Configure
        run: |
          cmake -S fuzzer -B fuzzer/build -G Ninja \
            -DCMAKE_C_COMPILER="${CC}" \
            -DCMAKE_CXX_COMPILER="${CXX}" \
            -DCMAKE_CXX_STANDARD=23 \
            -DCMAKE_CXX_STANDARD_REQUIRED=ON \
            -DOPENSSL_ROOT_DIR=/usr

      - name: Build
        run: cmake --build fuzzer/build

      - name: Verify
        run: ./fuzzer/build/Fuzzer -help=1
  docker-build-fuzzer:
    name: Test Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: false
          pull: false
          file: Dockerfile.fuzzer
          context: .
          tags: SUSE-26-03-Google/fuzzer:latest

  format:
    name: Check code format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'fuzzer/src'
          - 'fuzzer/include'
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Check format
        run: |
          cd ${{ matrix.path }}
          files=$(find . -type f \( -name '*.c' -o -name '*.cc' -o -name '*.h' -o -name '*.hpp' \))
          if [ -z "$files" ]; then
            echo "No C/C++ files found in ${{ matrix.path }}"
            exit 0
          fi
          clang-format --style=Google --dry-run --Werror $files

  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Build test image
        run: |
          docker build -f Dockerfile.test -t tpm-unit-tests .

      - name: Run unit tests
        run: |
          docker run --rm tpm-unit-tests
