name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build-fuzzer:
    name: Build Fuzzer binary
    # Provides OpenSSL 3.0.2
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake clang llvm libssl-dev ninja-build

      - name: Configure
        run: cmake -S fuzzer -B fuzzer/build -G Ninja

      - name: Build
        run: cmake --build fuzzer/build

      - name: Verify
        run: ./fuzzer/build/Fuzzer -help=1

  docker-build-fuzzer:
    name: Test Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: false
          pull: false
          file: Dockerfile.fuzzer
          context: .
          tags: SUSE-26-03-Google/fuzzer:latest

  format:
    name: Check code format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'fuzzer/src'
          - 'fuzzer/include'
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Check format
        uses: jidicula/clang-format-action@v4.16.0
        with:
          clang-format-version: '21'
          check-path: ${{ matrix.path }}
          fallback-style: 'Google'

  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Build test image
        run: |
          docker build -f Dockerfile.test -t tpm-unit-tests .

      - name: Run unit tests
        run: |
          docker run --rm tpm-unit-tests
